services:
  postgres:
    image: postgres
    container_name: local_pgdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=payment_app
    ports:
      - "6543:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - redis:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:mysecret@postgres:5432/payment_app?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis

  asynqmon:
    image: hibiken/asynqmon
    ports:
      - "8083:8083"
    command: ["--redis-addr=redis:6379", "--port=8083"]

volumes:
  local_pgdata:
  pgadmin-data:
  redis: